cat("====================     R Packages install start     ====================")
install.packages("plyr", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("rjson", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("rmongodb", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("rJava", repos="http://cran.nexr.com/")
cat("==========================================================================")
