cat("====================     R Packages install start     ====================")
install.packages("rmongodb_1.8.0.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("rjson_0.2.15.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("rJava_0.9-6.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("RSclient_0.7-2.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("plyr_1.8.3.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("CEMS_0.2.tar.gz", repos=NULL, type="source")
cat("==================     R Packages install complete.     ==================")
